usb_cam:
  ros__parameters:
    framerate: 15.0
    image_width: 640
    image_height: 480
    pixel_format: yuyv
    io_method: mmap


    #Adaptaciones a luz y cambios de color
    #brightness: 10
    #autoexposure: true
    #exposure: 40
    #auto_white_balance: true
    #white_balance: 4000
